// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "THE AREA ZONE", "        THE AREA ZONE                                                                              GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                          ALEX POMORSKI PRESENTS THE                                                            GALLERY&nbsp ZONE    ABOUT&nbsp ZONE    SOCIAL&nbsp ZONE                                                          ALL RIGHTS RESERVED 👁️ AREAZONE.ORG                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ", "");
   this[database_length++] = new SearchPage("GalleryZone.html", "THE AREA ZONE", "        THE AREA ZONE                                                                            GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                          GALLERY ZONE                                    CURRICULUM VITAE  CV RÉSUMÉ                      VIDEO!                                                                                                                                        OTHER STUFF!                                                                      Old &amp  Cringe                              ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("AboutZone.html", "THE AREA ZONE", "        THE AREA ZONE                                                                            GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                          ABOUT ZONE                                      WHO IS THIS GUY? Alex Charles Pomorski, terrestrial human avatar of the Area Zone Likes creating things with a narrative Hoping to do that for a living.CURRICULUM VITAE  CV  &amp  RÉSUMÉLIKES  art, movies, shows, animation, computer software, digital art, electronic/synthwave/metal/mashup music, anarchism, etc WHAT IS THE AREA ZONE?  The Area Zone was originally created as a website on some ancient 90's website maker with an intentionally vague and redundant name It is basically my central online hub Also, it is an unknowable eldritch entity beyond the comprehension of mere mortals                               ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("SocialZone.html", "THE AREA ZONE", "        THE AREA ZONE                                                                                GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                                          Please enable JavaScript to view the comments powered by Disqus    SEND EMAIL    SOCIAL ZONEWHEN YOU GAZE LONG INTO THE ABYSS, THE ABYSS ALSO GAZES BACK INTO YOU AND MAYBE REPLIES Leave us a message, like, comment, subscribe, send us death threats - it's the internet, do whatever! • IWHI Podcast! •                                                    ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("IWHI.html", "THE AREA ZONE", "        THE AREA ZONE                                                                              GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                                THE AREA ZONE PRESENTS                                        I WANNA HATE IT!Hate Movies, Not People unless they're jerks RSS  https //anchor.fm/s/754f86b4/podcast/rss▲ Use our RSS feed with your favorite podcatcher! ▲ Listen on Spotify for Podcasters  Listen on Regular Spotify  Listen on YouTube Leave comments and suggestions suggestion at IWannaHateIt@gmail.com!If it's not hate mail, we'll mention you in our next episode!SOCIAL MEDIA IWHI YouTube  IWHI Facebook  IWHI Discord  IWHI Twitter Listen to our latest episode right now and be sure to leave a comment!                    I Wanna Hate It  IWHI  is a podcast where a pair of idiots break down movies and shows Before watching, we view a trailer and declare whether we want to hate it, love it, or think it'll be cheesy  off-air, we watch it and take studious notes  lastly, we record a post-watch section recapping what we just saw so that we can definitively tell you, the audience, whether we hated it or not! We also have fun segments such as a death battle against previous episode characters, trivia, goofs, and educational content for the whole family!  NOTE  IWHI contains content not suitable for the whole family       IWHI FILM RANKING LIST, BEST TO WORST  as of episode 22      Deadpool &amp  Wolverine  2024  &amp  Aliens  Romulus  2024     Bad Lieutenant  Port of Call  New Orleans     Batman &amp  Robin  1997   because Arden would not allow it to be ranked lower than The Batman     The Batman  starring Bob Bats     Jurassic World Dominion  based on nostalgia alone      A tie between  Fear and Loathing in Las Vegas &amp  Soldier  starring the badass Kurt Russell as Todd Soldier  &amp  Sholay  1975     The Super Mario Bros Movie Part 2  2023     xXx  starring Van Diesel     Michael Keaton Batman 3  The Flash  2023     Blood Freak    Carnosaur    Krull    The Guyver    Super Mario Bros Part 1  1993     Morbius    Donnie Darko    Gummo  more like “GUM-NO,” am I right?     Old Boy 2003 &amp  Funny Games  2007                                   ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("Deviceman.html", "THE AREA ZONE", "        THE AREA ZONE                                                                              GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                                THE AREA ZONE PRESENTS             A MAN WHO FIGHTS CRIME… WITH DEVICES!      LINKS  Deviceman Issue #1 on Amazon Kindle  Deviceman Issue #2 on Amazon Kindle  Deviceman Issue #1 on Patreon  free   Deviceman on WebToons  free   Deviceman Facebook More to come when I have the time! For now, check my Instagram for updates!Issues #1 &amp  #2  free!                                                                                  ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("StingOps.html", "THE AREA ZONE", "        THE AREA ZONE                                                                              GALLERY ZONE      ABOUT ZONE      SOCIAL ZONE                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY&nbsp ZONE  &nbsp ABOUT&nbsp ZONE  &nbsp SOCIAL&nbsp ZONE                                AYE BEEGHE PRESENTS             A 1980's Action Film - Today!              LINKS  Sting Ops Treatment Google Doc  Sting Ops Production Google Doc  Sting Ops Shot List Google Sheets  Sting Ops Concept Art Google Slides  Sting Ops Script Google Doc  Sting Ops Facebook Group Aye Beeghe  Facebook, YouTube                                        ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   this[database_length++] = new SearchPage("OldGallery.html", "THE AREA ZONE", "        THE AREA ZONE                                                GALLERY/PORTFOLIO AREA  Old &amp  Cringe!       GALLERY/PORTFOLIO AREA Old &amp  Cringe!                       ILLUSTRATION &amp  DESIGN Portfolio PDF   Writing Samples   DeviantArt                                                                                                                                                                               VIDEO PRODUCTION          ANIMATIONS                                           Area Zone YouTube  Area Zone Vimeo           NEWGROUNDS FLASH ANIMATIONS  old school &amp  immature               OTHER LINKS &amp  STUFF             Guides and notes for various software, hardware, art, etc                                     My Animations          Collaborations                                                        Gallery      About      Social                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY  &nbsp ABOUT  &nbsp SOCIAL                                  ALL RIGHTS RESERVED 👁️ AREAZONE.ORG         ", "");
   return this;
}
