// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "THE AREA ZONE", "        THE AREA ZONE                                          ALEX POMORSKI PRESENTS THEAREA ZONETHE ZONE OF AREAS                                                       GALLERY    CURRENT&nbsp PROJECTS    ABOUT                                  All Rights Reserved • Email  theareazone@gmail.com                                                  Gallery      News/current projects      About      Contact                                                                                    AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                   ", "");
   this[database_length++] = new SearchPage("Gallery.html", "THE AREA ZONE", "        THE AREA ZONE                                          GALLERY/PORTFOLIO AREA  Old!                       ILLUSTRATION &amp  DESIGN Portfolio PDF   Writing Samples   DeviantArt                                                                                                                                                                               VIDEO PRODUCTION                           Area Zone YouTube  Area Zone Vimeo           ANIMATIONS                          NEWGROUNDS FLASH ANIMATIONS  old school &amp  immature                     My Animations          Collaborations              OTHER LINKS &amp  STUFF             Guides and notes for various software, hardware, art, etc                                                               Gallery      News/current projects      About      Contact                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                                  All Rights Reserved • Email  theareazone@gmail.com         ", "");
   this[database_length++] = new SearchPage("About.html", "THE AREA ZONE", "        THE AREA ZONE                                      THE ABOUT ZONE                WHO IS THIS GUY? Alex Pomorski, Michigan resident, terrestrial human avatar of the Area Zone Likes creating things with a narrative Wound up in the Marine Corps in Japan for a few years but now back to school, pursuing the dream of becoming a starving artist in the capitalist hellscape of Earth I guess this website sort of functions as his portfolio or whatever WORK HISTORY • United States Marine Corps, Micro-Miniature Avionics Technician, 2015 - 2020&nbsp  • Other work stuff that doesn't matter because it can't top being in the Marine Corps  everything before 2015  EDUCATION HISTORY • Savannah College of Art &amp  Design, Sequential Art MFA, 2021 to Present • Columbus State Community College, 24 credits Certificates in Digital Painting, Digital Design and Graphics, Advanced InDesign and Illustrator 2019 to 2020 • United States Marine Corps, IASSC Certified Lean Six Sigma Yellow Belt certification 2016 First-degree black belt martial arts instructor in the Marine Corps Martial Arts program 2019 • Eastern Michigan University, 100 credit hours, Bachelor’s in Criminology with a concentration in Law Enforcement, 2009 to 2011 Additional Information Technology courses until 2013 with a CompTIA A+  2009 edition  Essentials Certification in 2012 • Saginaw Valley State University, 16 credits with 6 transfer credit hours toward a degree in Criminology, 2008 to 2009 • Huron Valley Ambulance, Certified EMT and National Registry of Emergency Medical Technicians  NREMT  license and MI State certification 2013 • The Inn at St John’s, Service Etiquette Training, 2012&nbsp  • Washtenaw Community College, 69 credit hours, 24 credits toward film, 45 toward criminology and other courses, Certified Nurse Assistant, 2006 to 2014&nbsp  • RCTC  Regional Career Technical Center at Ypsilanti High School , Certificates for Advanced Adobe Photoshop, Desktop Publishing, Adobe Photoshop, and Desktop Publishing using Adobe InDesign, 2005-2006 Likes  shows, movies, sci-fi, animation, electronic/synthwave/darkwave/breakbeat/industrial/metal/mashup music, 3D printing, computers, digital art, truth, justice, anarchism - all the good stuff           WHAT IS THIS SITE FOR? WHAT IS THE POINT?          The Area Zone was originally created as a website on some ancient 90's website maker It is basically my central online hub that exists outside of social media                                                     Gallery      News/current projects      About      Contact                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                                  All Rights Reserved • Email  theareazone@gmail.com         ", "");
   this[database_length++] = new SearchPage("Contact.html", "THE AREA ZONE", "        THE AREA ZONE                                                                  Please enable JavaScript to view the comments powered by Disqus        SEND EMAIL    CONTACT PLACE    WHEN YOU GAZE LONG INTO THE ABYSS, THE ABYSS ALSO GAZES BACK INTO YOU AND MAYBE REPLIES Leave us a message, like, comment, subscribe, send us death threats - it's the internet, do whatever!                                                           Gallery      News/current projects      About      Contact                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                                  All Rights Reserved • Email  theareazone@gmail.com         ", "");
   this[database_length++] = new SearchPage("StingOps.html", "THE AREA ZONE", "        THE AREA ZONE                                                  AYE BEEGHE PRESENTS             A 1980's Action Film - Today!              LINKS  Sting Ops Treatment Google Doc  Sting Ops Production Google Doc  Sting Ops Shot List Google Sheets  Sting Ops Concept Art Google Slides  Sting Ops Script Google Doc  Sting Ops Facebook Group Aye Beeghe  Facebook, YouTube                                                        Gallery      News/current projects      About      Contact                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                                  All Rights Reserved • Email  theareazone@gmail.com         ", "");
   this[database_length++] = new SearchPage("Deviceman.html", "THE AREA ZONE", "        THE AREA ZONE                                                  THE AREA ZONE PRESENTS             A MAN WHO FIGHTS CRIME… WITH DEVICES!      LINKS  Deviceman Issue #1 on Amazon Kindle  Deviceman Issue #1 on Patreon  free   Deviceman on WebToons  free   Deviceman Facebook                                                                                                 Gallery      News/current projects      About      Contact                        &#8230                   AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                                  All Rights Reserved • Email  theareazone@gmail.com         ", "");
   this[database_length++] = new SearchPage("News&Projects.html", "THE AREA ZONE", "        THE AREA ZONE                                                                            Gallery      News/current projects      About      Contact                                                      AREA ZONE&nbsp &nbsp &nbsp       &nbsp GALLERY/PORTFOLIO  &nbsp NEWS/CURRENT&nbsp PROJECTS  &nbsp ABOUT  &nbsp CONTACT                          AREA ZONE NEWS AND CURRENT PROJECTS                                                                                                                                                                      VIDEO!                                            OTHER STUFF!                                                    All Rights Reserved • Email  theareazone@gmail.com         ", "");
   return this;
}
